# Generated by Django 5.2.4 on 2025-08-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_number', models.IntegerField(default=0)),
                ('flight_from', models.CharField(max_length=100)),
                ('flight_to', models.CharField(max_length=100)),
                ('flight_departure_time', models.TimeField()),
                ('flight_date', models.DateField()),
                ('flight_ticket_price', models.IntegerField(default=0)),
            ],
        ),
    ]
