# Generated by Django 5.2.4 on 2025-08-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_bookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
