# Generated by Django 5.2.4 on 2025-08-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_bookingmodel_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='flight',
            new_name='flight_name',
        ),
    ]
