# Generated by Django 5.2.4 on 2025-08-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_rename_flight_bookingmodel_flight_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='status',
        ),
    ]
