# Generated by Django 5.2.4 on 2025-08-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_remove_bookingmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
